version: "3.7"

volumes:
  db:

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=federation
      - MYSQL_USER=federation
      - MYSQL_PASSWORD=federation
    volumes:
      - db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
