# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# The API requires write permission on the repository to submit coverage reports
permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.4'

    - id: govulncheck
      uses: golang/govulncheck-action@v1

    - name: Lint
      run: gofmt -l -e ./

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Coverage
      uses: gwatts/go-coverage-action@v1.3.0
      with:
        # Fail the build if the coverage drops below supplied percentage
        coverage-threshold: 0 # Change this as coverage improves
        # Fail the build if coverage drops below coverage-threshold.  One of "always", "never" or "only_pull_requests"
        fail-coverage: only_pull_requests
        # Adds a comment to the PR with coverage information if true. If false will only add an action summary report
        add-comment: true
        # One or more regular expressions matching filenames to exclude from coverage statistics (e.g. for generated Go files)
        #ignore-pattern:
